### ISSUE TITLE
TASK 3.2.1.3: Design UI to create a new user

### ISSUE THREAD

**Issue by Ikramkamal** [samjamhen/Watermelons-soen341projectW2024#101]
## Task Description
As a developer, I want to display a button "Add user" on the user list page. When system administrator click on it, a new page with a form is displayed to create a new user with the following fields: 
- User Type
- Username
- Email
- Password
A submit button is displayed on the bottom of the form. 

## Acceptance Criteria
- [x] Add user button is displayed
- [x] A new page with a form is displayed 
- [x] Form can be submitted using submit button
