### ISSUE TITLE
TASK 3.2.3.2: Design UI for removing / modifying a user

### ISSUE THREAD

**Issue by Ikramkamal** [samjamhen/Watermelons-soen341projectW2024#103]
## Task Description: 
As a developer, I want to display two buttons on the bottom of the user's information page:
Modify: The details of the user are unlocked and can be modified
Remove: A Popup is asking System Administrator to confirm the decision to proceed with the deletion of user.

## Acceptance Criteria

- [x] Remove and Modify bottons are displayed
- [x] Modify button unlock user's information on the form
- [x] Remove button popup the confirmation message

**Comment by Ikramkamal** [comment]
UI for Modifying and Delete client is done.
