### ISSUE TITLE
TASK 1.4.1.3 Integrate backend functionality to sign up users with frontend

### ISSUE THREAD

**Issue by bxnjiho** [samjamhen/Watermelons-soen341projectW2024#245]
#### Task Description
As a developer, I want to integrate the user sign-up functionality with the frontend

#### Acceptance Criteria
- [x] Backend API to sign-up users is successfully integrated with the frontend, allowing customers to create an account
- [x] The created user account should be stored in the database with all provided user data
- [x] The customer should be able login with the created account
