### ISSUE TITLE
TASK 1.4.2.2: Backend functionality to login

### ISSUE THREAD

**Issue by bxnjiho** [samjamhen/Watermelons-soen341projectW2024#251]
#### Task Description
As a developer, I want to be implement a user login endpoint

#### Acceptance Criteria
- [x] The API endpoint should be accessible via the route "api/users/login"
- [x] The endpoint should validate input data and return appropriate error responses for invalid input
- [x] Successfully logging into a  user account should return a 200 status code along with the user object in the response body.
