### ISSUE TITLE
Task 4.1.2: Create request form

### ISSUE THREAD

**Issue by Ikramkamal** [samjamhen/Watermelons-soen341projectW2024#299]
## Task Description
As a developer, I want to create a form for customers who want to put their car for rent. The form should be similaire to the form used to add new vehicle by system administrator.

## Acceptance Criteria:

- [x] The request button redirect to a form
- [ ] Form is implemented with all required fields
- [ ] Customer can submit the form

**Comment by OGHO-SAYE** [comment]
completed
