### ISSUE TITLE
TASK 3.2.1.2: Backend functionality to create new users

### ISSUE THREAD

**Issue by bxnjiho** [samjamhen/Watermelons-soen341projectW2024#52]
#### Task Description
As a developer, I want to be implement a user creation endpoint

#### Acceptance Criteria
- [x] The API endpoint should be accessible via the route "api/users/"
- [x] The endpoint should validate input data and return appropriate error responses for invalid input
- [x] Successfully creating a new user account should return a 200 status code along with the newly created user object in the response body.
- [x] The created user account should be stored in the database with all provided user data.
