### ISSUE TITLE
TASK 1.3.1.1: Design UI for a "My Reservations" page

### ISSUE THREAD

**Issue by samjamhen** [samjamhen/Watermelons-soen341projectW2024#84]
## Task Description:
As a developer, I shall design a UI for customers to view their reservations

## Acceptance criteria
- [ ] Must match mockup on [figma](https://www.figma.com/file/1Tue47ygIN8LrrhG5ZQhPp/Rentaroo-Website-UI?type=design&node-id=0-1&mode=design&t=j3u0GXyxbym2h4nx-0)
- [ ] Must follow similar design to other pages on Webapp
- [ ] Display relevant information about reservation:
   - Images of vehicle
   - Reservation Dates
   - Time at which Reservation was made
   - Cost
   - Reservation Status
- [ ] Add "Edit Reservation" button
- [ ] Add "Cancel Reservation" button

**Comment by samjamhen** [comment]
Made a mistake by reopening. Closed by Yasmine.
