### ISSUE TITLE
TASK 1.3.2.1: Design UI for editable mode

### ISSUE THREAD

**Issue by samjamhen** [samjamhen/Watermelons-soen341projectW2024#87]
## Task Description
As a developer, I want to implement a transition to an editable UI after a user clicks on "Edit Reservation"

## Acceptance Criteria
- [x] UI transitions to an editable mode
  - Dropdown fields become active for reservation start date
  - Dropdown field become active for reservation end date
- [x] Highlight borders to indicate elements that are editable
- [x] "Save" button to save changes
- [x] "Cancel" button to discard changes
