### ISSUE TITLE
TASK 1.3.3.1: Design UI for Delete Reservation Confirmation Popup

### ISSUE THREAD

**Issue by samjamhen** [samjamhen/Watermelons-soen341projectW2024#89]
## Task Description:
As a developer, I want to design a UI popup for when a customer clicks on "Cancel Reservation"

## Acceptance Criteria
- [x] Popup Asking user to confirm their decision
- [x] "Confirm Cancellation" to proceed with deletion of reservation
- [x] "Back" button to discard changes
